// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import { UserProvider } from "./(main)/_context/UserContext";
import { FoodProvider } from "./(main)/_context/FoodContext";
import { CartProvider } from "./(main)/_context/CartContext";
import { CategoryProvider } from "./(main)/_context/CategoryContext";

const geistSans = localFont({
  src: "/fonts/Geist-Regular.woff2",
  variable: "--font-geist-sans",
  display: "swap",
  preload: true,
});

const geistMono = localFont({
  src: "/fonts/GeistMono-Regular.woff2",
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <CategoryProvider>
            <FoodProvider>
              <CartProvider>
                <Toaster />
                <main>{children}</main>
              </CartProvider>
            </FoodProvider>
          </CategoryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
