import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { UserProvider } from "./(main)/_context/UserContext";
import { FoodProvider } from "./(main)/_context/FoodContext";
import { CartProvider } from "./(main)/_context/CartContext";
import { CategoryProvider } from "./(main)/_context/CategoryContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#404040]`}
      >
        <UserProvider>
          <CategoryProvider>
            <FoodProvider>
              <CartProvider>
                <Toaster />
                <main>{children}</main>
              </CartProvider>
            </FoodProvider>
          </CategoryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
